  - name: unzip the hive to service directory
    action: unarchive src={{ source_dir }}/apache-hive-{{ hive_version }}-bin.tar.gz dest={{ service_dir }} copy=no
    when: with_hive
    tags:
     - hive
    environment:
     HIVE_HOME: "{{ service_dir }}/hive-{{ hive_version }}-bin/"

  - name: generate hive-site.xml for hive
    template: src=hive-site.xml dest={{ service_dir }}/apache-hive-{{ hive_version }}-bin/conf/hive-site.xml owner={{ remote_user }} mode=0644
    when: with_hive
    tags:
     - hive

  - name: generate hive-env.sh for hive
    template: src=hive-env.sh  dest={{ service_dir }}/apache-hive-{{ hive_version }}-bin/conf/hive-env.sh owner={{ remote_user }} mode=0644
    when: with_hive
    tags:
     - hive

  - name: put mysql driver into hive classpath
    action: copy src={{ source_dir }}/mysql-connector-java-5.1.24.jar dest={{ service_dir }}/apache-hive-{{ hive_version }}-bin/lib/mysql-connector-java-5.1.24.jar owner={{ remote_user }} mode=0644
    when: with_hive
    tags:
     - hive
  
  - name: mkdir for log files
    action: file path={{ service_dir }}/apache-hive-{{ hive_version }}-bin/log state=directory mode=0755
    when: with_hive
    tags:
     - hive
