---
# file: roles/zookeeper_server/tasks/main.yml

#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban-plugins/2.5.0/azkaban-hdfs-viewer-2.5.0.tar.gz
#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban2/2.5.0/azkaban-sql-script-2.5.0.tar.gz
#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban-plugins/2.5.0/azkaban-jobsummary-2.5.0.tar.gz
#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban2/2.5.0/azkaban-executor-server-2.5.0.tar.gz
#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban2/2.5.0/azkaban-web-server-2.5.0.tar.gz
#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban-plugins/2.5.0/azkaban-reportal-2.5.0.tar.gz
#  shell: chdir={{ source_dir }}  wget https://s3.amazonaws.com/azkaban2/azkaban-plugins/2.5.0/azkaban-jobtype-2.5.0.tar.gz


- name: unzip the Azkaban to service directory
  action: unarchive src={{ source_dir }}/azkaban-{{ azkaban_version }}.tar.gz dest={{ service_dir }} copy=no
  when: with_azkaban
  tags: azkaban

- name: configure azkaban conf
  template: src=zoo.cfg dest={{ service_dir }}/zookeeper-{{ azkaban_version }}/conf/zoo.cfg owner=azkaban group=azkaban mode=0644
  when: with_azkaban
  tags:
    - azkaban

- name: initialize azkaban
  # command: creates={{ service_dir }}/zookeeper-{{ zookeeper_version }}/myid service zookeeper-server init --myid={{ zookeeper_id }}
  shell: command echo {{azkaban_id }} > {{ service_dir }}/azkaban-{{ azkaban_version }}/myid
  when: with_azkaban
  tags: azkaban

- name: start azkaban
  command:  su - {{ remote_user }} -c "{{ service_dir }}/azkaban-{{ azkaban_version }}/bin/zkServer.sh start"
  when: with_azkaban
  tags: azkaban

